In [1]:
import pandas as pd
from pycaret.classification import *

In [3]:
df = pd.read_csv('study_plan.csv')
df

,Gender,Age,What time do you wake up in the morning?,What time do you have breakfast?,Are you doing a job?,"If you have a job, how much time do you spend on it?",How much time do you spend on education?,What time do you have lunch?,What is your hobby?,How much time does it take?,What time do you have dinner?,What Is Your University?,What is your Faculty?,What is your academic year?,What has been your GPA in the last years?,How many repeats did you have Last year?,What time do you go to bed at night?,How long does it take for a university outdoor activity ?,How much time do you take for Lab Sessions and practical's?
0,Female,28,5.00,7.00,Yes,2 hours,4 hours,13.30,Watching Movie,3 hours,21.00,NSBM Green University,School of Computing,Year 04,2.70,1,22.00,2 hours,2 hours
1,Female,21,3.00,10.00,No,NaN,5 hours,14.00,Playing,2 hours,22.00,CINEC Campus Sri Lanka,School of Computing,Year 03,3.00,5,22.30,3 hours,2 hours
2,Male,22,4.00,7.00,Yes,5 hours,3 hours,12.00,other,1 hours,22.30,Horizon University,School of Law,Year 03,3.20,0,23.45,3 hours,6 hours
3,Male,27,2.00,8.00,No,NaN,7 hours,12.30,Watching Movie,4 hours,20.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 03,1.80,6,23.00,2 hours,5 hours
4,Male,23,1.00,7.30,Yes,6 hours,1 hours,13.30,Reading,2 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 04,1.00,0,1.00,1 hours,4 hours
5,Male,24,6.00,8.30,Yes,10 hours,2 hours,13.45,other,3 hours,19.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 03,3.80,6,2.30,5 hours,2 hours
6,Male,26,8.00,10.00,No,NaN,5 hours,15.00,Playing,2 hours,20.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 01,2.90,3,23.45,6 hours,3 hours
7,Male,28,9.00,10.30,Yes,5 hours,5 hours,14.30,Reading,1 hours,20.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,1.87,9,22.30,2 hours,2 hours
8,Male,30,4.00,8.30,No,NaN,6 hours,15.30,other,3 hours,19.45,NSBM Green University,School of Computing,Year 03,2.63,5,21.30,3 hours,1 hours
9,Female,24,3.00,6.45,No,NaN,3 hours,14.00,other,4 hours,19.30,CINEC Campus Sri Lanka,School of Computing,Year 02,3.25,3,20.00,4 hours,3 hours
10,Male,22,6.00,7.30,No,NaN,2 hours,14.30,other,5 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 03,1.25,4,2.30,1 hours,8 hours
11,Male,23,7.00,8.30,No,NaN,10 hours,16.00,Watching Movie,3 hours,22.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 01,1.89,3,3.00,4 hours,7 hours
12,Male,29,7.00,8.00,Yes,6 hours,2 hours,14.45,Watching Movie,2 hours,22.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,2.45,0,1.45,3 hours,6 hours
13,Female,24,2.00,9.00,No,NaN,4 hours,15.00,Playing,3 hours,21.00,NSBM Green University,School of Business,Year 03,3.65,2,1.30,1 hours,5 hours
14,Male,22,5.00,10.00,No,NaN,5 hours,15.00,Watching Movie,1 hours,21.45,CINEC Campus Sri Lanka,School of Engineering,Year 01,1.89,1,1.30,2 hours,2 hours
15,Female,25,6.00,10.30,Yes,6 hours,1 hours,13.30,other,4 hours,22.00,NSBM Green University,School of Media Studies,Year 04,2.65,0,23.00,4 hours,3 hours
16,Female,23,7.00,8.45,Yes,7 hours,1 hours,13.45,Reading,3 hours,20.00,General Sir John Kotelawala Defence University,School of Hospitality,Year 03,3.45,0,22.30,3 hours,4 hours
17,Female,21,8.00,9.30,Yes,6 hours,2 hours,14.30,other,2 hours,20.30,NSBM Green University,School of Engineering,Year 02,2.40,4,21.00,5 hours,5 hours
18,Male,20,9.00,10.45,No,NaN,8 hours,15.00,other,3 hours,19.45,National Institute of Business Management,School of Business,Year 03,3.20,3,21.45,2 hours,6 hours
19,Male,18,10.00,11.45,Yes,8 hours,1 hours,12.30,other,2 hours,19.30,ESOFT Metro Campus,School of Computing,Year 04,1.90,5,3.00,1 hours,8 hours
20,Male,24,5.00,7.30,No,NaN,5 hours,12.45,other,4 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,2.67,8,2.00,3 hours,7 hours
21,Male,26,11.30,12.30,Yes,6 hours,2 hours,13.00,other,3 hours,21.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 04,2.35,5,23.45,4 hours,2 hours
22,Female,24,3.00,7.30,No,NaN,10 hours,14.30,Playing,5 hours,21.00,NSBM Green University,School of Business,Year 02,2.32,4,21.30,1 hours,6 hours
23,Female,21,5.00,7.00,Yes,2 hours,6 hours,13.00,Reading,2 hours,23.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 01,3.24,0,22.00,2 hours,3 hours
24,Female,28,5.30,6.30,No,NaN,7 hours,15.30,Watching Movie,3 hours,23.30,NSBM Green University,School of Business,Year 02,2.00,2,1.00,3 hours,4 hours
25,Female,30,6.30,8.00,Yes,6 hours,2 hours,12.00,Playing,4 hours,23.00,Horizon University,School of Engineering,Year 03,3.64,3,2.00,5 hours,2 hours
26,Female,27,7.00,8.00,Yes,8 hours,3 hours,12.30,other,2 hours,22.00,National Institute of Business Management,School of Media Studies,Year 04,1.75,4,21.00,4 hours,3 hours
27,Female,27,8.30,10.00,No,NaN,5 hours,13.35,Playing,3 hours,22.30,National Institute of Business Management,School of Media Studies,Year 03,1.60,5,22.30,3 hours,5 hours
28,Female,24,7.00,9.00,No,NaN,6 hours,15.00,Watching Movie,2 hours,22.00,General Sir John Kotelawala Defence University,School of Architecture,Year 03,2.30,6,22.45,2 hours,6 hours
29,Female,26,5.00,6.30,No,NaN,8 hours,15.30,Reading,3 hours,20.00,ESOFT Metro Campus,School of Law,Year 04,1.45,4,23.00,1 hours,7 hours
30,Male,23,6.00,7.30,No,NaN,10 hours,14.30,Playing,5 hours,20.30,CINEC Campus Sri Lanka,School of Law,Year 04,2.36,3,21.45,2 hours,8 hours
31,Male,21,5.30,7.45,Yes,2 hours,3 hours,14.00,Reading,2 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 01,2.89,1,21.30,4 hours,2 hours
32,Male,22,6.45,8.00,Yes,2 hours,4 hours,13.00,Reading,3 hours,19.30,NSBM Green University,School of Business,Year 04,2.75,3,1.30,3 hours,1 hours
33,Female,20,4.30,8.30,Yes,10 hours,1 hours,12.30,other,2 hours,20.00,Sri Lanka Institute of Information Technology ...,School of Business,Year 03,1.85,3,2.00,1 hours,2 hours
34,Female,20,5.45,7.00,Yes,4 hours,6 hours,12.45,Playing,2 hours,20.30,Sri Lanka Institute of Information Technology ...,School of Business,Year 02,2.36,1,2.30,2 hours,3 hours
35,Male,25,6.00,8.00,Yes,2 hours,3 hours,13.00,Watching Movie,3 hours,22.00,Horizon University,School of Business,Year 02,1.47,2,3.00,3 hours,5 hours
36,Female,26,3.15,6.30,No,NaN,10 hours,13.30,Reading,1 hours,22.30,NSBM Green University,School of Business,Year 01,3.21,8,3.30,1 hours,6 hours
37,Male,24,3.00,7.00,Yes,8 hours,4 hours,14.00,Reading,5 hours,19.30,General Sir John Kotelawala Defence University,School of Business,Year 02,3.68,2,4.00,2 hours,4 hours
38,Female,25,5.45,9.00,No,NaN,9 hours,14.30,Reading,3 hours,19.45,ESOFT Metro Campus,School of Business,Year 01,2.65,1,20.45,4 hours,2 hours
39,Female,26,6.00,7.00,Yes,10 hours,2 hours,12.30,Watching Movie,4 hours,22.00,National Institute of Business Management,School of Media Studies,Year 02,1.96,3,20.30,3 hours,7 hours
40,Male,28,7.00,8.00,No,NaN,5 hours,13.00,other,6 hours,21.00,CINEC Campus Sri Lanka,School of Engineering,Year 03,3.24,5,21.30,1 hours,8 hours
41,Female,23,9.00,10.30,No,NaN,3 hours,13.30,Playing,3 hours,21.30,Sri Lanka Institute of Information Technology ...,School of Engineering,Year 04,2.30,5,22.00,2 hours,3 hours
42,Female,22,7.00,10.00,No,NaN,7 hours,14.30,Playing,2 hours,20.30,ESOFT Metro Campus,School of Media Studies,Year 03,2.65,7,21.00,4 hours,2 hours
43,Female,24,8.00,10.30,Yes,2 hours,2 hours,14.45,Watching Movie,4 hours,19.00,CINEC Campus Sri Lanka,School of Business,Year 02,1.65,5,23.00,3 hours,5 hours
44,Female,18,10.00,11.00,Yes,4 hours,4 hours,13.30,other,5 hours,19.30,ESOFT Metro Campus,School of Media Studies,Year 03,3.10,4,22.50,2 hours,1 hours
45,Male,19,10.30,11.00,Yes,5 hours,6 hours,12.00,Playing,3 hours,18.30,Sri Lanka Institute of Information Technology ...,School of Business,Year 01,3.70,8,3.00,4 hours,2 hours
46,Male,28,11.00,12.00,Yes,6 hours,4 hours,13.45,other,2 hours,23.00,ESOFT Metro Campus,School of Media Studies,Year 04,2.68,3,23.00,5 hours,3 hours
47,Male,30,8.00,9.00,No,NaN,7 hours,13.00,Playing,2 hours,22.30,General Sir John Kotelawala Defence University,School of Engineering,Year 02,1.98,6,2.00,3 hours,4 hours
48,Male,24,5.00,7.00,No,NaN,8 hours,14.45,Watching Movie,4 hours,22.00,General Sir John Kotelawala Defence University,School of Computing,Year 03,1.85,5,1.00,2 hours,8 hours
49,Male,23,6.00,7.00,No,NaN,10 hours,15.00,Watching Movie,5 hours,21.00,NSBM Green University,School of Architecture,Year 03,2.36,6,1.30,1 hours,6 hours
50,Male,22,7.00,8.30,No,NaN,6 hours,12.30,other,2 hours,20.00,Horizon University,School of Computing,Year 04,3.40,5,2.30,4 hours,5 hours
51,Male,26,3.30,7.30,No,NaN,8 hours,13.35,Playing,3 hours,20.30,Horizon University,School of Computing,Year 04,2.30,1,3.00,5 hours,2 hours
52,Female,29,4.30,7.00,No,NaN,10 hours,14.30,other,6 hours,20.45,Sri Lanka Institute of Information Technology ...,School of Law,Year 04,3.10,2,23.00,2 hours,4 hours
53,Male,30,6.00,7.45,Yes,10 hours,2 hours,14.00,Watching Movie,2 hours,19.30,Sri Lanka Institute of Information Technology ...,School of Media Studies,Year 01,1.95,4,20.15,2 hours,2 hours
54,Male,27,2.30,6.00,No,NaN,4 hours,15.00,Watching Movie,1 hours,19.00,NSBM Green University,School of Engineering,Year 01,2.43,4,1.30,1 hours,3 hours
55,Male,28,10.30,11.30,Yes,8 hours,2 hours,15.30,other,2 hours,19.30,Sri Lanka Institute of Information Technology ...,School of Engineering,Year 01,2.80,0,3.00,3 hours,5 hours
56,Male,25,5.00,6.30,Yes,3 hours,6 hours,12.30,Watching Movie,3 hours,20.00,Horizon University,School of Business,Year 02,2.35,0,20.30,4 hours,6 hours
57,Female,23,6.00,7.30,Yes,8 hours,1 hours,12.00,Playing,2 hours,20.30,National Institute of Business Management,School of Engineering,Year 03,3.40,0,20.00,6 hours,4 hours
58,Male,22,7.00,8.30,No,NaN,5 hours,13.00,other,1 hours,22.00,General Sir John Kotelawala Defence University,School of Media Studies,Year 02,1.98,0,21.00,2 hours,5 hours
59,Female,21,5.00,6.45,Yes,2 hours,6 hours,13.30,Playing,5 hours,21.00,General Sir John Kotelawala Defence University,School of Computing,Year 03,1.36,3,22.00,3 hours,2 hours
60,Female,24,4.00,5.30,Yes,4 hours,2 hours,14.30,Playing,2 hours,21.00,CINEC Campus Sri Lanka,School of Architecture,Year 04,2.65,4,1.30,1 hours,4 hours
61,Male,25,3.00,7.00,Yes,6 hours,3 hours,14.00,Reading,2 hours,20.00,Rajarata university,School of Business,Year 02,2.70,0,23.00,2 hours,3 hours
62,Female,23,3.00,6.00,No,NaN,6 hours,15.00,Playing,3 hours,20.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,2.38,3,19.00,4 hours,5 hours
63,Male,20,4.00,6.30,Yes,6 hours,2 hours,13.00,other,1 hours,19.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 03,3.25,5,19.30,1 hours,6 hours
64,Female,21,5.00,6.45,No,NaN,8 hours,13.30,Playing,2 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,3.60,4,20.30,2 hours,7 hours
65,Male,20,6.00,8.00,Yes,2 hours,2 hours,15.00,Watching Movie,4 hours,18.30,NSBM Green University,School of Computing,Year 03,3.80,4,19.45,3 hours,8 hours
66,Female,23,2.00,8.30,No,NaN,3 hours,14.30,Watching Movie,5 hours,21.00,NSBM Green University,School of Computing,Year 02,1.90,3,21.00,2 hours,2 hours
67,Male,25,1.00,6.00,Yes,8 hours,1 hours,12.30,Watching Movie,2 hours,20.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 04,1.36,6,22.00,4 hours,1 hours
68,Male,26,1.30,7.00,Yes,10 hours,2 hours,15.30,Watching Movie,2 hours,20.00,National Institute of Business Management,School of Business,Year 03,3.20,2,3.45,5 hours,3 hours
69,Male,28,8.00,10.00,No,NaN,6 hours,14.30,Playing,3 hours,21.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,2.60,7,3.00,6 hours,4 hours
70,Male,29,9.00,10.30,Yes,10 hours,3 hours,14.45,Watching Movie,4 hours,22.00,NSBM Green University,School of Computing,Year 04,2.47,3,1.30,2 hours,5 hours
71,Male,30,2.45,7.30,No,NaN,7 hours,13.30,Playing,2 hours,22.30,Sri Lanka Institute of Information Technology ...,School of Engineering,Year 02,2.13,2,2.45,1 hours,3 hours
72,Male,21,3.00,7.00,No,NaN,6 hours,13.00,Playing,3 hours,21.30,Sri Lanka Institute of Information Technology ...,School of Engineering,Year 02,3.69,2,23.00,3 hours,6 hours
73,Male,22,4.00,6.00,Yes,6 hours,2 hours,14.00,Reading,2 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,3.45,1,22.00,4 hours,4 hours
74,Male,24,8.00,10.00,No,NaN,3 hours,12.30,Playing,2 hours,19.00,NSBM Green University,School of Business,Year 03,2.14,2,21.30,2 hours,7 hours
75,Female,27,9.00,10.30,No,NaN,5 hours,13.00,Playing,4 hours,20.00,NSBM Green University,School of Business,Year 02,1.93,4,1.30,5 hours,6 hours
76,Male,28,5.00,6.45,Yes,4 hours,8 hours,13.30,Watching Movie,2 hours,23.00,NSBM Green University,School of Computing,Year 02,3.65,2,2.00,1 hours,3 hours
77,Female,27,7.00,8.45,Yes,6 hours,2 hours,14.00,Reading,3 hours,21.30,Horizon University,School of Business,Year 02,2.75,2,2.30,3 hours,2 hours
78,Female,24,7.30,8.00,No,NaN,10 hours,15.00,Playing,4 hours,20.30,NSBM Green University,School of Computing,Year 03,2.89,4,1.30,2 hours,1 hours
79,Male,25,7.45,8.30,No,NaN,9 hours,14.30,other,5 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 04,1.98,3,1.45,5 hours,5 hours
80,Male,23,6.45,9.00,Yes,6 hours,2 hours,13.00,other,3 hours,20.00,CINEC Campus Sri Lanka,School of Architecture,Year 03,3.40,4,2.45,2 hours,4 hours
81,Female,21,3.00,8.00,Yes,3 hours,6 hours,13.00,Playing,2 hours,21.00,General Sir John Kotelawala Defence University,School of Architecture,Year 02,2.65,6,3.00,1 hours,2 hours
82,Female,20,4.30,10.00,Yes,8 hours,1 hours,12.00,Playing,3 hours,21.30,ESOFT Metro Campus,School of Hospitality,Year 02,1.96,6,23.30,2 hours,3 hours
83,Female,22,5.00,6.30,Yes,6 hours,2 hours,12.30,other,2 hours,22.00,National Institute of Business Management,School of Law,Year 03,2.34,8,21.30,2 hours,6 hours
84,Female,26,6.00,7.00,Yes,2 hours,3 hours,14.30,Playing,2 hours,23.00,NSBM Green University,School of Engineering,Year 02,3.21,4,20.50,3 hours,1 hours
85,Male,28,3.30,7.30,Yes,7 hours,1 hours,14.00,Playing,3 hours,20.00,Horizon University,School of Computing,Year 03,2.95,1,19.00,4 hours,2 hours
86,Male,29,2.45,6.30,No,NaN,2 hours,15.00,other,1 hours,20.30,NSBM Green University,School of Computing,Year 02,3.20,4,20.00,2 hours,4 hours
87,Male,30,8.00,9.00,No,NaN,6 hours,15.30,other,4 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 04,1.96,3,22.00,5 hours,5 hours
88,Male,24,9.30,10.00,Yes,5 hours,4 hours,13.30,Watching Movie,2 hours,19.30,NSBM Green University,School of Engineering,Year 03,2.36,2,21.30,3 hours,6 hours
89,Female,25,10.00,10.30,No,NaN,5 hours,13.40,Reading,3 hours,23.00,National Institute of Business Management,School of Business,Year 03,3.20,3,20.30,2 hours,2 hours
90,Female,26,3.45,7.00,No,NaN,3 hours,14.30,Playing,3 hours,22.30,NSBM Green University,School of Media Studies,Year 04,3.65,7,21.30,4 hours,8 hours
91,Male,21,5.00,6.45,No,NaN,7 hours,14.00,Watching Movie,2 hours,20.30,ESOFT Metro Campus,School of Engineering,Year 04,1.78,5,22.00,2 hours,2 hours
92,Female,20,6.30,7.00,No,NaN,10 hours,14.45,other,2 hours,21.00,CINEC Campus Sri Lanka,School of Business,Year 01,3.10,4,21.00,3 hours,4 hours
93,Female,21,4.50,8.00,Yes,2 hours,3 hours,13.30,Watching Movie,4 hours,21.30,NSBM Green University,School of Computing,Year 04,3.65,1,23.00,1 hours,5 hours
94,Male,27,7.45,8.45,Yes,6 hours,2 hours,15.30,other,3 hours,20.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 01,2.78,0,20.00,2 hours,6 hours
95,Female,23,10.00,11.00,No,NaN,7 hours,13.00,Playing,4 hours,20.30,Sri Lanka Institute of Information Technology ...,School of Computing,Year 03,2.96,7,1.45,5 hours,2 hours
96,Female,30,8.00,9.00,No,NaN,3 hours,13.30,Playing,5 hours,19.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,3.60,5,2.00,2 hours,2 hours
97,Male,19,9.00,10.00,Yes,8 hours,1 hours,12.30,Reading,3 hours,19.30,NSBM Green University,School of Business,Year 02,1.75,2,3.00,1 hours,4 hours
98,Male,25,7.00,9.00,No,NaN,3 hours,14.00,Watching Movie,2 hours,22.00,Sri Lanka Institute of Information Technology ...,School of Computing,Year 02,3.24,4,3.30,2 hours,3 hours

In [3]:
cat_features = ['Category Number', 'Rating No']
experiment = setup(df, target='Meal Plan No', categorical_features=cat_features)

In [4]:
best_model = compare_models()

In [5]:
top3 = compare_models(n_select = 3)

In [6]:
save_model(top3[0], model_name='meal_plan_naive_bayes')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=['Category Number',
                                                             'Rating No'],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[],
                                       target='Meal Plan No',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_val...
                 ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                 ('cluster_all', 'passthrough'),
                 ('dummy', Dummify(target='Meal Plan No')),
                 ('fix_perfect', Remove_100(target='Meal Plan No')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  GaussianNB(priors=None, var_smoothing=1e-09)]],
          verbose=False),
 'meal_plan_naive_bayes.pkl')